### ISSUE TITLE
Credit Card NFC

### ISSUE THREAD

**Issue by tpharaoh** [capawesome-team/capacitor-nfc-demo#12]
I am testing the demo, I recently tried an android add, which could. read a NFC credit card.
Now I tried your package. in IOS says can't connect to NFC

Anything I need to update?

**Comment by robingenz** [comment]
This plugin currently only supports NDEF. It is planned to add NFC raw commands support in Q4 2022 (see Roadmap) which might help you with that.

**Comment by tpharaoh** [comment]
`2022-11-11 20:18:36.015964+0200 App[9959:3565542] [CoreNFC] -[NFCTagReaderSession _connectTag:error:]:730 Error Domain=NFCError Code=2 "Missing required entitlement" UserInfo={NSLocalizedDescription=Missing required entitlement}
`
using the new 0.3.0

I used all entitlements:
<?xml version="1.0" encoding="UTF-8"?>
```
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>com.apple.developer.nfc.readersession.formats</key>
	<array>
		<string>TAG</string>
		<string>NDEF</string>
		<string>PACE</string>
	</array>
</dict>
</plist>
```

am I maybe missing something still?

I should add, in android it shows some data on screen, Tag Identifier and Technologies, but not the card data I expected.

**Comment by robingenz** [comment]
You get this error with your app or with this demo app?

**Comment by tpharaoh** [comment]
demo app

I figured I would test all functionality with demo app first.

So, the above error in IOS.

In android it shows identifier and technologies, but not all the raw data I know is associated

**Comment by robingenz** [comment]
I just tested it again on my end and it worked without problems.
Please change the app identifier in XCode and make sure that you are logged in with your Apple Developer account and app signing is set up correctly (automatic signing without warnings/errors in XCode).

> In android it shows identifier and technologies, but not all the raw data I know is associated

What exactly do you mean by "raw data"? The demo app only reads NDEF entries on the `read` page. If you want to retrieve other data, you have to send a custom raw command according to the specification of the tag via the `transceive` page.

**Comment by tpharaoh** [comment]
I clearly don't understand enough about reading card details... I'll need to research more.

As for IOS, I have a custom app identifier, and am logged into my dev account in xcode. It signs, build, even scans NFC. It just returns an error. But I can continue dev with Android until I figure it out

**Comment by robingenz** [comment]
Please also check that you have the latest version of this app. There was a bug recently which caused this kind of error.

**Comment by tpharaoh** [comment]
[https://github.com/7s4r/credit-card-reader/blob/master/src/nfc.js](https://github.com/7s4r/credit-card-reader/blob/master/src/nfc.js)

I don't seem to have the skill to read credit card data with this package. I found the above repo of someone who made a PC based, nodejs package. I wonder if someone here has the needed skillset and would like to make an offer to make just a demo (I will integrate myself later into our inhouse CRM)
