### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by gungorkdr** [capawesome-team/capacitor-nfc-demo#27]
Hi, when I try to "npm i" I'm facing with this error below.

```
npm ERR! code E401
npm ERR! 401 Unauthorized - GET https://npm.pkg.github.com/download/@capawesome-team/capacitor-nfc/5.0.2/972e469916ac2b711158b10a9f5fe0fd922c36fb - authentication token not provided
```
Can you please help me to solve this issue?

**Comment by robingenz** [comment]
Please take a look at [Common issues](https://capawesome.io/insiders/getting-started/#common-issues).
