### ISSUE TITLE
Not authorized

### ISSUE THREAD

**Issue by C0DE-L00P** [capawesome-team/capacitor-nfc-demo#29]
I am trying to run the project starting by cloning it then with "npm i" this error came up

```
 ERR_PNPM_FETCH_401  GET https://npm.pkg.github.com/@capawesome-team%2Fcapacitor-nfc: Unauthorized - 401

This error happened while installing a direct dependency of C:\Users\Mohamed Gamal\3D Objects\_STU\test

No authorization header was set for the request.
```

**Comment by robingenz** [comment]
Hi @C0DE-L00P,
you must have access to the Capawesome Sponsorware ([Read more](https://capawesome.io/insiders/)) to install all necessary dependencies.

**Comment by hochun836** [comment]
Why not write the information about `Capawesome Sponsorware` in the `README.md` of this demo project ?

**Comment by robingenz** [comment]
@hochun836 You mean this line? https://github.com/capawesome-team/capacitor-nfc-demo/blob/71abe852ce5e372dc26fbcd92a04e26c5856e8a9/README.md?plain=1#L18

**Comment by hochun836** [comment]
Sorry, I miss this line. 😥 But, maybe make it more obvious
