### ISSUE TITLE
Issue with NFC Demo App's transceive Function in NfcV Format

### ISSUE THREAD

**Issue by baglikow** [capawesome-team/capacitor-nfc-demo#31]
Hello!

I am facing an issue while using the NFC Demo App provided. I am using a Google Pixel Pro 8 device and have not made any modifications to the app's source code. When attempting to use the transceive function in NfcV format with my tag, I encounter the error "ERROR_TAG_NOT_CONNECTED" due to tagTechnology and tagTechnologyClass being null.

Device: Google Pixel Pro 8
Tag Format: NfcV
Error: ERROR_TAG_NOT_CONNECTED

It is worth noting that the read function of the app works flawlessly, successfully reading tags in NfcV format. The NFC tag being used should not be the cause of the issue, as the equivalent of the transceive function in another app functions correctly with the same tag.

I would appreciate assistance in troubleshooting and resolving this issue. Thank you.

**Comment by robingenz** [comment]
Thank you for your request. I need more information to be able to reproduce the problem:
- Which tag are you using exactly?
- Which command are you sending to the tag?

Please also attach a screen recording showing exactly which steps you are performing.

**Comment by baglikow** [comment]
I'm using the ST25DV64KC and send 02:AD:02:0D to read the tags dynamic register as described on page 22 in this document: https://www.st.com/resource/en/application_note/an4910-data-exchange-between-wired-ic-and-wireless-rf-iso-15693-using-fast-transfer-mode-supported-by-st25dvi2c-series-stmicroelectronics.pdf

https://github.com/user-attachments/assets/eab144f2-504c-45d4-8173-c723eefe2c46

**Comment by robingenz** [comment]
@baglikow There was a breaking change in Capacitor NFC v6.0.0. Since version 6.0.0 you have to call `connect` under Android before you can use the `transceive` method. I forgot to add this breaking change to the demo app.

**Comment by baglikow** [comment]
Thank you for addressing the error! Your fix worked for me related to the Google Pixel 8 Pro.
However, I have encountered a new and maybe similar problem when testing the app on an iPhone:

![IMG_D30343CA6C18-1](https://github.com/user-attachments/assets/301bb6df-2d03-4f1a-bbbd-7571ef54d89b)

As the error remains on the iPhone, I was wondering if the code adjustments made for Android also need to be implemented for iOS compatibility.

Thank you for your attention to this matter!

**Comment by robingenz** [comment]
@baglikow Yes, this was another missing feature. I've just added it: https://github.com/capawesome-team/capacitor-nfc-demo/commit/4118c338c6e41a8014f96f88928d59fd3b524b73

Please note that this is only a simple demo app to show the basic functionality. Not every feature is supported by the demo app.
